<%@ Page Title="Agregar Apartado de Area" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="RealizarApartadoArea.aspx.cs" Inherits="RealizarApartadoArea" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <asp:MultiView ID="mvApartadosAreas" runat="server">

        <asp:View ID="vAgregarApartadosAreas" runat="server">

            

                

        </asp:View>

        <asp:View ID="vApartadosAreas" runat="server">

            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                <asp:LinkButton ID="btnAgregarApartado" runat="server" Text="Agregar" 
                    CssClass="btn btn-primary" onclick="btnAgregarApartado_Click">
                    <i class="glyphicon glyphicon-plus"></i> Agregar Apartado de Area
                </asp:LinkButton>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                <asp:LinkButton ID="btnBuscarEspecifico" runat="server" Text="Agregar" 
                    CssClass="btn btn-primary">
                    <i class="glyphicon glyphicon-plus"></i> Buscar Apartado Especifico
                </asp:LinkButton>
            </div>

            <div align="right" id="BuscarEnGrid" runat="server" class="divFiltro">
                Buscar Apartado de Area:
                <input type="text" id="FilterTextBox" name="FilterTextBox" />                   
            </div>

            <div class="divGrid scroll">
                <asp:GridView ID="gridApartadosAreas" runat="server" CssClass="grid" 
                    AutoGenerateDeleteButton="True" 
                    onrowdeleted="gridApartadosAreas_RowDeleted" 
                    onrowdeleting="gridApartadosAreas_RowDeleting" >
                </asp:GridView>
             </div>

        </asp:View>

    </asp:MultiView>

</asp:Content>

